#!/bin/bash
# /home/boxbox/create_iso.sh "%F" "%N" "%G" "%D" "%L" "%R" "%C" "%Z" "%I"
sleep 2

path="$3"

cd "$path"

for dir in */; do
    genisoimage -o "${dir%/}.iso" -R -J -joliet-long "$dir" && rm -r "$dir"
done
